Rodrigom/finetuning embedding
snova-jorgep/ai-starter-kit pull request #13
Opened 2024-09-03 18:34 UTC by snova-rodrigom

- Added support to auth issues workaround
- Adapted job progress logic
- Adapted list checkpoints code
- Adapted promote checkpoint code

2024-09-03 19:19 UTC, snova-jorgep requested changes

2024-09-03 19:19 UTC, snova-jorgep commented on utils/fine_tuning/config.yaml
can we let this file with previous llms config?

2024-09-03 19:19 UTC, snova-jorgep commented on utils/fine_tuning/config.yaml
given now we have a config one for embeddings with custom config?

2024-09-03 19:19 UTC, snova-jorgep commented on utils/fine_tuning/src/snsdk_wrapper.py
>                  project_id = create_project_response["id"]
this line is duplicated

2024-09-06 16:10 UTC, snova-rodrigom commented on utils/fine_tuning/config.yaml
sure thing, I've reverted that config to the original state

2024-09-06 16:11 UTC, snova-rodrigom reviewed
commented on fixes coming from @snova-jorgep

2024-09-06 16:41 UTC, snova-jorgep approved these changes

2024-09-06 16:42 UTC, merged